###############################################################################
# 11_mvpf_stress_test.R -- Figure 4.8 panels (MVPF stress-test: beta -> MVPF)
#
# TWO separate panels (saved as separate PDF/PNG files) for Chapter 4.8:
#   Panel A: id_9  Dranove, Ody & Starc (2021)  -- NON-Laffer (safe) zone.
#   Panel B: id_420 Bailey & Goodman-Bacon (2015) -- Laffer zone.
#
# No embedded titles, no in-plot caption; titles and caption live in the
# LaTeX figure environment (see overleaf/Chapters/Chapter4.tex, Lesson 8).
# Labels are pushed off the curve via nudge_y + force_pull tuning in
# geom_text_repel.
#
# Source: analysis/mvpf_stress_test_long.csv (generated by mvpf_pilots.R)
#
# Output: output/figures/figure_4_8_mvpf_stress_test_panelA.pdf (+png)
#         output/figures/figure_4_8_mvpf_stress_test_panelB.pdf (+png)
###############################################################################

suppressPackageStartupMessages({
  library(ggplot2); library(dplyr); library(tidyr); library(ggrepel); library(scales)
})

base_dir <- getwd()
out_dir  <- file.path(base_dir, "output", "figures")
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

# ------------------------------------------------------------------
# Load the Spec-A point estimates used in Table 4.8
# ------------------------------------------------------------------
st <- read.csv(file.path(base_dir, "analysis/mvpf_stress_test_long.csv"),
               stringsAsFactors = FALSE)

st <- st %>% mutate(
  spec_label = case_when(
    spec == "TWFE_with_ctrls"         ~ "TWFE + ctrls",
    spec == "CS_NT_with_ctrls_static" ~ "CS-DR static",
    spec == "CS_NT_with_ctrls_dyn"    ~ "CS-DR dynamic"
  ),
  spec_label = factor(spec_label,
                      levels = c("TWFE + ctrls", "CS-DR static", "CS-DR dynamic"))
)

# ------------------------------------------------------------------
# MVPF helpers (mirror mvpf_pilots.R so we can draw smooth curves)
# ------------------------------------------------------------------
mvpf_mc_drug <- function(beta_lnprice, drug_share = 0.15, wtp = 1.0) {
  fe <- drug_share * (exp(beta_lnprice) - 1)
  G  <- 1 + fe
  wtp / G
}

mvpf_chc_elderly <- function(beta_deaths_per_100k,
                             alpha = 0.015, lambda = 0.015,
                             baseline_wtp = 1.0) {
  wtp <- baseline_wtp + alpha * (-beta_deaths_per_100k)
  G   <- 1 + lambda * beta_deaths_per_100k
  wtp / G
}

# ==================================================================
# PANEL A -- id_9 Dranove et al. (2021)
# ==================================================================
st9  <- st %>% filter(paper_id == 9)

beta_grid_9 <- seq(-0.32, 0.12, by = 0.002)
curve_9 <- data.frame(
  beta = beta_grid_9,
  mvpf = sapply(beta_grid_9, mvpf_mc_drug, drug_share = 0.15, wtp = 1.0)
)

# Deterministic label offsets: push each label off the curve (vertically).
# Points lie on a nearly-linear curve from (-0.3, 1.04) down to (0.1, 0.985);
# pushing TWFE up and CS-DR points down gives clean separation.
st9 <- st9 %>% mutate(
  nudge_y_val = c(0.012, -0.010, -0.018),   # TWFE up; CS-DR static down; CS-DR dyn further down
  nudge_x_val = c(0.04, -0.08, 0.05)
)

panel_A <- ggplot() +
  geom_hline(yintercept = 1.0, linetype = "dotted",
             color = "grey50", linewidth = 0.4) +
  geom_line(data = curve_9, aes(x = beta, y = mvpf),
            color = "#08519c", linewidth = 0.9) +
  geom_point(data = st9,
             aes(x = beta, y = mvpf, shape = spec_label, fill = spec_label),
             size = 4, color = "black", stroke = 0.5) +
  geom_text_repel(
    data = st9,
    aes(x = beta, y = mvpf,
        label = sprintf("%s\n\u03B2=%+.3f, MVPF=%.3f",
                        spec_label, beta, mvpf)),
    size = 3,
    nudge_y       = st9$nudge_y_val,
    nudge_x       = st9$nudge_x_val,
    box.padding   = 0.7,
    point.padding = 0.5,
    force         = 8,
    force_pull    = 0.2,
    min.segment.length = 0,
    segment.size  = 0.3,
    segment.color = "grey40",
    direction     = "both",
    max.overlaps  = Inf,
    seed          = 7
  ) +
  scale_shape_manual(values = c(21, 22, 23)) +
  scale_fill_manual(values = c("#d62728", "#ff7f0e", "#2ca02c")) +
  coord_cartesian(ylim = c(0.95, 1.055), xlim = c(-0.32, 0.14)) +
  labs(
    x = expression(paste(hat(beta), "  (", Delta, " log price per prescription)")),
    y = "MVPF"
  ) +
  guides(shape = "none", fill = "none") +
  theme_minimal(base_size = 11) +
  theme(
    panel.grid.minor = element_blank(),
    plot.title       = element_blank(),
    plot.subtitle    = element_blank(),
    plot.caption     = element_blank(),
    plot.margin      = margin(t = 4, r = 8, b = 4, l = 4)
  )

ggsave(file.path(out_dir, "figure_4_8_mvpf_stress_test_panelA.pdf"),
       panel_A, width = 7.5, height = 4.8, device = cairo_pdf)
ggsave(file.path(out_dir, "figure_4_8_mvpf_stress_test_panelA.png"),
       panel_A, width = 7.5, height = 4.8, dpi = 150)

# ==================================================================
# PANEL B -- id_420 Bailey & Goodman-Bacon (2015)
# ==================================================================
st420 <- st %>% filter(paper_id == 420)

beta_grid_420 <- seq(-65, 25, by = 0.1)
curve_420 <- data.frame(
  beta = beta_grid_420,
  mvpf = sapply(beta_grid_420, mvpf_chc_elderly)
) %>% filter(is.finite(mvpf), mvpf < 30 & mvpf > -5)

# Deterministic nudges for Panel B:
#   TWFE (β=-53, MVPF=8.91): label to the right, slightly below
#   CS-DR static (β=-6.8, MVPF=1.23): label upward, to the left
#   CS-DR dynamic (β=+7.5, MVPF=0.80): label downward, to the right
st420 <- st420 %>% mutate(
  nudge_y_val = c(-2.5, 2.0, -1.2),
  nudge_x_val = c(18, -14, 6)
)

panel_B <- ggplot() +
  geom_hline(yintercept = 1.0, linetype = "dotted",
             color = "grey50", linewidth = 0.4) +
  geom_hline(yintercept = 0, linetype = "solid",
             color = "grey70", linewidth = 0.3) +
  geom_line(data = curve_420, aes(x = beta, y = mvpf),
            color = "#a50f15", linewidth = 0.9) +
  geom_point(data = st420,
             aes(x = beta, y = mvpf, shape = spec_label, fill = spec_label),
             size = 4, color = "black", stroke = 0.5) +
  geom_text_repel(
    data = st420,
    aes(x = beta, y = mvpf,
        label = sprintf("%s\n\u03B2=%+.1f, MVPF=%.2f",
                        spec_label, beta, mvpf)),
    size = 3,
    nudge_y       = st420$nudge_y_val,
    nudge_x       = st420$nudge_x_val,
    box.padding   = 0.8,
    point.padding = 0.6,
    force         = 6,
    force_pull    = 0.3,
    min.segment.length = 0,
    segment.size  = 0.3,
    segment.color = "grey40",
    direction     = "both",
    max.overlaps  = Inf,
    seed          = 42
  ) +
  scale_shape_manual(values = c(21, 22, 23)) +
  scale_fill_manual(values = c("#d62728", "#ff7f0e", "#2ca02c")) +
  coord_cartesian(ylim = c(-1, 13), xlim = c(-68, 28)) +
  labs(
    x = expression(paste(hat(beta), "  (elderly mortality per ", 10^5, ")")),
    y = "MVPF"
  ) +
  guides(shape = "none", fill = "none") +
  theme_minimal(base_size = 11) +
  theme(
    panel.grid.minor = element_blank(),
    plot.title       = element_blank(),
    plot.subtitle    = element_blank(),
    plot.caption     = element_blank(),
    plot.margin      = margin(t = 4, r = 8, b = 4, l = 4)
  )

ggsave(file.path(out_dir, "figure_4_8_mvpf_stress_test_panelB.pdf"),
       panel_B, width = 7.5, height = 4.8, device = cairo_pdf)
ggsave(file.path(out_dir, "figure_4_8_mvpf_stress_test_panelB.png"),
       panel_B, width = 7.5, height = 4.8, dpi = 150)

# ==================================================================
# SUMMARY TO STDOUT
# ==================================================================
cat("\n=== Figure 4.8 MVPF stress-test (panels saved separately) ===\n")
cat("Panel A (id_9 Dranove et al.):\n")
print(st9  %>% select(spec, beta, G, mvpf), row.names = FALSE)
cat("\nPanel B (id_420 Bailey & Goodman-Bacon):\n")
print(st420 %>% select(spec, beta, G, mvpf), row.names = FALSE)

cat("\nSaved:\n")
cat(" ", file.path(out_dir, "figure_4_8_mvpf_stress_test_panelA.pdf"), "\n")
cat(" ", file.path(out_dir, "figure_4_8_mvpf_stress_test_panelA.png"), "\n")
cat(" ", file.path(out_dir, "figure_4_8_mvpf_stress_test_panelB.pdf"), "\n")
cat(" ", file.path(out_dir, "figure_4_8_mvpf_stress_test_panelB.png"), "\n")
cat("\nDone: 11_mvpf_stress_test.R\n")
